version: "2.4"
services:
  terraform:
    image: quay.io/azavea/terraform:0.12.29
    volumes:
      - ./:/usr/local/src
      - $HOME/.aws:/root/.aws:ro
    environment:
      - AWS_PROFILE=${AWS_PROFILE:-noaa}
      - GIT_COMMIT=${GIT_COMMIT:-latest}
      - NOAA_FLOOD_MAP_DEBUG=1
      - NOAA_FLOOD_MAP_SETTINGS_BUCKET=${NOAA_FLOOD_MAP_SETTINGS_BUCKET:-noaafloodmap-staging-config-us-east-1}
    working_dir: /usr/local/src
    entrypoint: bash
