version: '2.4'
services:
  catalogs:
    image: noaa-flood-catalogs
    build: ./catalogs
    environment:
      - AWS_PROFILE=${AWS_PROFILE:-noaa}
      - SENTINELHUB_OAUTH_ID
      - SENTINELHUB_OAUTH_SECRET
    volumes:
      - ./catalogs:/opt/catalogs
      - $HOME/.aws:/root/.aws:ro

  pipeline:
    image: noaa-flood-pipeline
    build: ./pipeline
