#!/bin/bash

set -e

if [[ -n "${NOAA_FLOOD_MAP_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Publish container images to Elastic Container Registry (ECR).
"
}

if [[ -n "${GIT_COMMIT}" ]]; then
    GIT_COMMIT="${GIT_COMMIT:0:7}"
else
    GIT_COMMIT="$(git rev-parse --short HEAD)"
fi

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        if [[ -n "${NOAA_AWS_ECR_ENDPOINT}" ]]; then
            # Evaluate the return value of the get-login subcommand, which
            # is a docker login command with temporarily ECR credentials.
            eval "$(aws ecr get-login --no-include-email)"

            docker tag "noaa-flood-catalogs:${GIT_COMMIT}" \
                "${NOAA_AWS_ECR_ENDPOINT}/noaa-flood-catalogs:${GIT_COMMIT}"
            docker tag "noaa-flood-pipeline:${GIT_COMMIT}" \
                "${NOAA_AWS_ECR_ENDPOINT}/noaa-flood-pipeline:${GIT_COMMIT}"

            docker push "${NOAA_AWS_ECR_ENDPOINT}/noaa-flood-catalogs:${GIT_COMMIT}"
            docker push "${NOAA_AWS_ECR_ENDPOINT}/noaa-flood-pipeline:${GIT_COMMIT}"
        else
            echo "ERROR: No NOAA_AWS_ECR_ENDPOINT variable defined."
            exit 1
        fi
    fi
fi
